In [3]:
!pip install numpy

In [4]:
import numpy as np

In [5]:
a =np.array(64)

In [6]:
print(a)

64


In [7]:
type(a)

numpy.ndarray

In [8]:
print(a.ndim)

0


In [9]:
b=np.array([[[2,5,1],[4,4,6]],[[2,3,7],[5,6,8]]])

In [10]:
print(b)

[[[2 5 1]
  [4 4 6]]

 [[2 3 7]
  [5 6 8]]]


In [11]:
print(b.ndim)

3


In [12]:
first_numpy=[1.0,2,3]

In [13]:
first_numpy

[1.0, 2, 3]

In [14]:
a=np.array(first_numpy)

In [15]:
a

array([1., 2., 3.])

In [16]:
a.dtype

dtype('float64')

In [17]:
a.ndim

1

In [18]:
a.size

3

In [19]:
a.shape

(3,)

In [20]:
np.zeros(2)

array([0., 0.])

In [21]:
list1 =[[24,51,3,5],[74,85,96,7],[41,52,63,2],[4,5,6,4]]

In [22]:
y=np.array(list1)

In [23]:
y

array([[24, 51,  3,  5],
       [74, 85, 96,  7],
       [41, 52, 63,  2],
       [ 4,  5,  6,  4]])

In [24]:
np.arange(0,24,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
y.ndim

2

In [28]:
y.shape

(4, 4)

In [29]:
y.itemsize

4

In [30]:
y.nbytes

64

In [31]:
list2 =[[24,51,3,5],[74,85,96,7],[41,52,63,2],[4,5,6,4]]

In [32]:
p =np.array(list2)

In [33]:
p

array([[24, 51,  3,  5],
       [74, 85, 96,  7],
       [41, 52, 63,  2],
       [ 4,  5,  6,  4]])

In [34]:
p[1,3]

7

In [35]:
p[ :,2] #coloum

array([ 3, 96, 63,  6])

In [36]:
p[2]#row

array([41, 52, 63,  2])

In [37]:
list3 =[[24,51,3,5],[74,85,96,7],[41,52,63,2],[4,5,6,4]]

In [38]:
c=np.array(list3)

In [39]:
print(c)

[[24 51  3  5]
 [74 85 96  7]
 [41 52 63  2]
 [ 4  5  6  4]]


In [40]:
c.ndim

2

In [41]:
e=np.zeros((4,1))

In [42]:
e

array([[0.],
       [0.],
       [0.],
       [0.]])

In [43]:
s =np.ones((2,3,4))

In [44]:
s

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [45]:
s=np.full((2,3),33)#full arys to fill the same number in the matrix .np.full(())

In [46]:
s

array([[33, 33, 33],
       [33, 33, 33]])

In [47]:
s=np.identity(3)

In [48]:
s

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
q=np.array([2,3,34,4,23,5])   #copy function

In [50]:
a=q.copy()

In [51]:
a[2]=12

In [52]:
q

array([ 2,  3, 34,  4, 23,  5])

In [53]:
a

array([ 2,  3, 12,  4, 23,  5])

In [54]:
q.copy()

array([ 2,  3, 34,  4, 23,  5])

In [55]:
a

array([ 2,  3, 12,  4, 23,  5])

In [56]:
a+2 #arithmaatic operations includes in numpy

array([ 4,  5, 14,  6, 25,  7])

In [57]:
a**2

array([  4,   9, 144,  16, 529,  25])

In [58]:
a-2

array([ 0,  1, 10,  2, 21,  3])

In [59]:
a%2

array([0, 1, 0, 0, 1, 1], dtype=int32)

In [60]:
q-3

array([-1,  0, 31,  1, 20,  2])

In [61]:
s =np.linspace(0,10,5) #linspace

In [62]:
s

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [63]:
snap=np.arange(0,20,5)

In [64]:
snap

array([ 0,  5, 10, 15])

In [65]:
s=np.zeros((4,3))

In [66]:
s

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [67]:
np.ones((3,2,1))

array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]])

In [68]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
 n=np.identity(2)

In [70]:
n

array([[1., 0.],
       [0., 1.]])

In [71]:
n.ndim

2

In [72]:
np.random.rand(1,20)

array([[0.67286369, 0.55905154, 0.29272184, 0.35193879, 0.02077319,
        0.31310416, 0.09259841, 0.03272719, 0.39396301, 0.49079875,
        0.42336821, 0.21161529, 0.73413278, 0.89678579, 0.85392687,
        0.57325806, 0.97388307, 0.8185764 , 0.95488338, 0.38572375]])

In [73]:
np.random.randint(0,5,10)

array([4, 1, 3, 1, 4, 1, 2, 1, 4, 4])

In [74]:
boy=np.arange(9)

In [75]:
boy

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [76]:
s=np.random.randint(0,30,10)

In [77]:
s

array([ 1, 18, 13,  5,  7, 26, 14, 23, 23, 21])

In [78]:
boy.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [79]:
s.max()

26

In [80]:
s.min()

1

In [81]:
s.shape

(10,)

In [82]:
s.argmax()

5

In [83]:
s.argmin()

0

In [84]:
boy.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
boy.shape

(9,)

In [86]:
#NUMPY ARRAY INDEXING SELECTION

In [87]:
a=np.array([12,3,6,8,7,2,9,2,17,16])

In [88]:
a

array([12,  3,  6,  8,  7,  2,  9,  2, 17, 16])

In [89]:
a[0]

12

In [90]:
a[5]

2

In [91]:
a[0:6]

array([12,  3,  6,  8,  7,  2])

In [92]:
a[:3]

array([12,  3,  6])

In [93]:
a[5:6]

array([2])

In [94]:
a[5:]

array([ 2,  9,  2, 17, 16])

In [95]:
len(a)

10

In [96]:
a

array([12,  3,  6,  8,  7,  2,  9,  2, 17, 16])

In [97]:
a[5:9]=12

In [98]:
a

array([12,  3,  6,  8,  7, 12, 12, 12, 12, 16])

In [99]:
a[1:5]+2

array([ 5,  8, 10,  9])

In [100]:
a[0:5]*0

array([0, 0, 0, 0, 0])

In [101]:
a[1:5]=100


In [102]:
a

array([ 12, 100, 100, 100, 100,  12,  12,  12,  12,  16])

In [103]:
a[0:2]=112

In [104]:
a

array([112, 112, 100, 100, 100,  12,  12,  12,  12,  16])

In [105]:
snap=a[0:5]

In [106]:
snap

array([112, 112, 100, 100, 100])

In [107]:
snap[:]=0

In [108]:
snap

array([0, 0, 0, 0, 0])

In [109]:
a

array([ 0,  0,  0,  0,  0, 12, 12, 12, 12, 16])

In [110]:
a.copy()

array([ 0,  0,  0,  0,  0, 12, 12, 12, 12, 16])

In [111]:
new_array=np.array([[2,5,8],[4,576,89],[23,45,12]])

In [112]:
new_array

array([[  2,   5,   8],
       [  4, 576,  89],
       [ 23,  45,  12]])

In [113]:
new_array[2][1]

45

In [114]:
new_array[:2,2:]

array([[ 8],
       [89]])

In [115]:
arr=np.arange(1,20)

In [116]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [117]:
rah=arr<5

In [118]:
rah                    # its represent the boolen values 

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [119]:
arr>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [120]:
arr[rah] # its returns the values 

array([1, 2, 3, 4])

In [121]:
arr[arr>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [122]:
x=np.arange(40).reshape(4,10)

In [123]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [124]:
x.ndim

2

In [125]:
x.dtype

dtype('int32')

In [126]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [127]:
x[:3,3:5]

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [128]:
# NUMPY OPERATERS

In [129]:
y=np.arange(1,30,2)

In [130]:
y

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [131]:
y + y

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58])

In [132]:
y- y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [133]:
y*2

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58])

In [134]:
y/2

array([ 0.5,  1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5,
       11.5, 12.5, 13.5, 14.5])

In [135]:
y +100

array([101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125,
       127, 129])

In [136]:
np.sqrt(y)

array([1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ,
       3.31662479, 3.60555128, 3.87298335, 4.12310563, 4.35889894,
       4.58257569, 4.79583152, 5.        , 5.19615242, 5.38516481])

In [137]:
np.exp(y)

array([2.71828183e+00, 2.00855369e+01, 1.48413159e+02, 1.09663316e+03,
       8.10308393e+03, 5.98741417e+04, 4.42413392e+05, 3.26901737e+06,
       2.41549528e+07, 1.78482301e+08, 1.31881573e+09, 9.74480345e+09,
       7.20048993e+10, 5.32048241e+11, 3.93133430e+12])

In [138]:
y.max()

29

In [139]:
y.min()

1