## NUMPY ARREYS

In [1]:
my_list =[1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
my_list =[1,2,3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
name = [[1,2,3],[4,5,6]]

In [7]:
np.array(name)

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
anjali = np.array([1,2,3])

In [9]:
anjali

array([1, 2, 3])

In [10]:
python = np.array([4,5,6])

In [11]:
python

array([4, 5, 6])

In [12]:
np.dot(anjali,python)

32

In [13]:
anjali*python

array([ 4, 10, 18])

In [14]:
(anjali*python).sum()

32

In [15]:
arr1 = np.array([1,2,3])

In [16]:
arr2 = np.array([4,5,6])

In [17]:
%time
arr1*arr2

CPU times: total: 0 ns
Wall time: 0 ns


array([ 4, 10, 18])

In [18]:
(arr1*arr2).sum()

32

In [19]:
%time
np.dot(arr1,arr2)

CPU times: total: 0 ns
Wall time: 0 ns


32

In [20]:
climate_data = np.array([[73,7,43],
                        [91,88,64],
                        [87,134,58]])
                

In [21]:
climate_data

array([[ 73,   7,  43],
       [ 91,  88,  64],
       [ 87, 134,  58]])

In [22]:

climate_data.shape

(3, 3)

In [23]:
anjali_name =np.array ([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9],
               [10, 11, 12]])

In [24]:
anjali_name.shape

(4, 3)

In [25]:
anjali_name.dtype

dtype('int32')

In [45]:
arr3=np.array([[[1,2,3],
       [1,2,3]],
       
      [[3,4,5],
       [3,4,5.1]]])


In [46]:
arr3.shape

(2, 2, 3)

In [56]:
arr31

array([[[1. , 2. , 3. ],
        [1. , 2. , 3. ]],

       [[3. , 4. , 5. ],
        [3. , 4. , 5.1]]])

In [47]:
anjali_name @ anjali

array([14, 32, 50, 68])

In [ ]:
# np.matmul(anjali_name,anjali)

## Silcing

In [60]:
arr = np.arange(0,10)

In [61]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
arr[0:7]

array([0, 1, 2, 3, 4, 5, 6])

In [65]:
arr[1:5]

array([1, 2, 3, 4])

In [70]:
arr[6:]

array([6, 7, 8, 9])

In [75]:
arr[0:8] = 100

In [76]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100,   8,   9])

In [79]:
arr = np.arange(0,6)

In [80]:
arr

array([0, 1, 2, 3, 4, 5])

In [81]:
slice_of_arr = arr[0:4]

In [83]:
slice_of_arr

array([0, 1, 2, 3])

In [84]:
slice_of_arr[:]=20

In [85]:
slice_of_arr

array([20, 20, 20, 20])

## Numpy methods

In [86]:
arr

array([20, 20, 20, 20,  4,  5])

In [107]:
np.zeros((1,2))

array([[0., 0.]])

In [122]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [123]:
np.linspace(1,2,3)

array([1. , 1.5, 2. ])

In [125]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [127]:
np.random.rand(5,5)

array([[0.52222852, 0.97980591, 0.78446651, 0.60427796, 0.1637793 ],
       [0.95881218, 0.00887108, 0.6911582 , 0.61991608, 0.53426809],
       [0.60555711, 0.78398578, 0.36468877, 0.12945227, 0.35424976],
       [0.80270844, 0.87377849, 0.62307641, 0.23520254, 0.47257186],
       [0.86774656, 0.8193752 , 0.47025504, 0.65073274, 0.23755231]])

In [39]:
np.random.randn(2,2)

array([[ 0.5173507 , -0.73743619],
       [ 0.29268548, -0.11019398]])

In [40]:
np.random.randint(1,100,10)

array([35, 87, 31, 89, 81, 41, 22, 93, 73, 57])

In [41]:
np.random.randint(1,20,5)

array([17,  4,  1,  8, 17])

In [ ]:
np.ones((2,3))

In [59]:
arr = np.arange(1,10)

In [60]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr.max()

9

In [62]:
arr.min()

1

In [63]:
arr.argmax()

8

In [69]:
arr.argmin()

0

In [73]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
bool_arr = arr<5

In [77]:
bool_arr

array([ True,  True,  True,  True, False, False, False, False, False])

In [78]:
bool_arr>4

array([False, False, False, False, False, False, False, False, False])

In [79]:
arr[bool_arr]

array([1, 2, 3, 4])

In [84]:
arr_2d = np.arange(50).reshape(5,10)

In [85]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [9]:
arr_3d =np.arange(30).reshape(3,10)

In [10]:
arr_3d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [11]:
arr_3d[1:3,3:5]

array([[13, 14],
       [23, 24]])