In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings("ignore")

# TASK-1

In [5]:
df=pd.read_csv("C:\\Users\\RAHUL\\Desktop\\kaggledata\\WL_task2.csv")

In [6]:
df

Unnamed: 0                     Date       Energy  Resistance  Current  \
0          16645  2023-03-10 16:06:05.180  5279.587891       272.0     7.10   
1          16650  2023-03-10 16:06:59.390  5284.775879       270.0     7.13   
2          16651  2023-03-10 16:00:49.570  5229.563965       267.0     7.15   
3          16660  2023-03-10 16:44:37.850  5402.745117       273.0     7.16   
4          16661  2023-03-10 16:45:25.860  5341.735840       274.0     7.10   
...          ...                      ...          ...         ...      ...   
8448       94288  2023-08-08 14:11:31.360  5510.055176       277.0     7.16   
8449       94289  2023-08-08 14:00:20.180  5404.756836       277.0     7.09   
8450       94290  2023-08-08 14:01:13.470  5384.125000       276.0     7.10   
8451       94291  2023-08-08 14:06:30.710  5395.432129       277.0     7.10   
8452       94292  2023-08-08 14:07:19.430  5414.668945       278.0     7.10   

      Voltage         Power  uipvalue weldpoint      score prediction  year  \
0        1.88  13342.919922        80     T0391   8.137701     Passed  2023   
1        1.84  13123.620117        96     T0391  15.128845     Passed  2023   
2        1.85  13218.250000        69     T0391  39.734211     Failed  2023   
3        1.90  13602.860352        93     T0391  16.287536     Passed  2023   
4        1.89  13413.139648        95     T0391   0.707636     Passed  2023   
...       ...           ...       ...       ...        ...        ...   ...   
8448     1.93  13828.259766       107     T0391  14.094838     Passed  2023   
8449     1.93  13691.419922       108     T0391   3.364030     Passed  2023   
8450     1.92  13623.940430       105     T0391   2.171779     Failed  2023   
8451     1.91  13556.799805       104     T0391   1.702148     Passed  2023   
8452     1.93  13703.000000       104     T0391   3.865788     Passed  2023   

      month  day     id  
0         3   10  Train  
1         3   10  Train  
2         3   10  Train  
3         3   10  Train  
4         3   10  Train  
...     ...  ...    ...  
8448      8    8   Test  
8449      8    8   Test  
8450      8    8   Test  
8451      8    8   Test  
8452      8    8   Test  

[8453 rows x 15 columns]

# prediction for resistance through the linear regression

In [7]:
df.shape

(8453, 15)

In [8]:
df.isna().sum()

Unnamed: 0    0
Date          0
Energy        0
Resistance    0
Current       0
Voltage       0
Power         0
uipvalue      0
weldpoint     0
score         0
prediction    0
year          0
month         0
day           0
id            0
dtype: int64

In [9]:
df.describe()

Unnamed: 0       Energy   Resistance      Current      Voltage  \
count   8453.000000  8453.000000  8453.000000  8453.000000  8453.000000   
mean   58932.415474  5379.251368   274.048622     7.121709     1.900485   
std    21263.023358    78.602977     3.386469     0.026122     0.026535   
min    16645.000000  5030.246094   253.000000     7.090000     1.790000   
25%    39911.000000  5326.129883   272.000000     7.100000     1.880000   
50%    58473.000000  5372.984863   274.000000     7.100000     1.900000   
75%    77522.000000  5425.247070   276.000000     7.130000     1.910000   
max    94292.000000  5799.580078   291.000000     7.340000     2.040000   

              Power     uipvalue        score    year        month  \
count   8453.000000  8453.000000  8453.000000  8453.0  8453.000000   
mean   13532.508092   101.978942    10.455755  2023.0     4.658346   
std      207.973221     8.502625    11.625749     0.0     1.667431   
min    12703.450195    62.000000     0.095840  2023.0     3.000000   
25%    13409.360352    97.000000     3.381011  2023.0     3.000000   
50%    13529.750000   102.000000     7.147864  2023.0     4.000000   
75%    13671.780273   106.000000    14.244948  2023.0     6.000000   
max    14615.160156   141.000000   281.813421  2023.0     8.000000   

               day  
count  8453.000000  
mean     15.173430  
std       8.715896  
min       1.000000  
25%       8.000000  
50%      15.000000  
75%      23.000000  
max      31.000000

In [10]:
a=df[["Energy","Current","Voltage","Power"]]

In [11]:
b=df["Resistance"].values

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test =train_test_split(a,b,test_size=0.2)

In [13]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [14]:
lr_prd=reg.predict(x_test)

In [15]:
lr_prd

array([271.55210248, 282.15423601, 276.13178332, ..., 278.03304625,
       270.6610319 , 274.60836176])

In [16]:
reg.score(x_test,y_test)

0.9403001398998072

# prediction for pass and fail through the logistic regression

In [17]:
df

Unnamed: 0                     Date       Energy  Resistance  Current  \
0          16645  2023-03-10 16:06:05.180  5279.587891       272.0     7.10   
1          16650  2023-03-10 16:06:59.390  5284.775879       270.0     7.13   
2          16651  2023-03-10 16:00:49.570  5229.563965       267.0     7.15   
3          16660  2023-03-10 16:44:37.850  5402.745117       273.0     7.16   
4          16661  2023-03-10 16:45:25.860  5341.735840       274.0     7.10   
...          ...                      ...          ...         ...      ...   
8448       94288  2023-08-08 14:11:31.360  5510.055176       277.0     7.16   
8449       94289  2023-08-08 14:00:20.180  5404.756836       277.0     7.09   
8450       94290  2023-08-08 14:01:13.470  5384.125000       276.0     7.10   
8451       94291  2023-08-08 14:06:30.710  5395.432129       277.0     7.10   
8452       94292  2023-08-08 14:07:19.430  5414.668945       278.0     7.10   

      Voltage         Power  uipvalue weldpoint      score prediction  year  \
0        1.88  13342.919922        80     T0391   8.137701     Passed  2023   
1        1.84  13123.620117        96     T0391  15.128845     Passed  2023   
2        1.85  13218.250000        69     T0391  39.734211     Failed  2023   
3        1.90  13602.860352        93     T0391  16.287536     Passed  2023   
4        1.89  13413.139648        95     T0391   0.707636     Passed  2023   
...       ...           ...       ...       ...        ...        ...   ...   
8448     1.93  13828.259766       107     T0391  14.094838     Passed  2023   
8449     1.93  13691.419922       108     T0391   3.364030     Passed  2023   
8450     1.92  13623.940430       105     T0391   2.171779     Failed  2023   
8451     1.91  13556.799805       104     T0391   1.702148     Passed  2023   
8452     1.93  13703.000000       104     T0391   3.865788     Passed  2023   

      month  day     id  
0         3   10  Train  
1         3   10  Train  
2         3   10  Train  
3         3   10  Train  
4         3   10  Train  
...     ...  ...    ...  
8448      8    8   Test  
8449      8    8   Test  
8450      8    8   Test  
8451      8    8   Test  
8452      8    8   Test  

[8453 rows x 15 columns]

In [18]:
from sklearn import preprocessing                    
label_encoder= preprocessing.LabelEncoder()          
df['prediction'] = label_encoder.fit_transform(df['prediction'])     
df['prediction'].value_counts()

prediction
1    6379
0    2074
Name: count, dtype: int64

In [19]:
x=df[["Energy","Resistance","Current","Voltage","Power","uipvalue","score","year","month","day"]]

In [20]:
y=df["prediction"].values

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [22]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_train,Y_train)

LogisticRegression()

In [23]:
lr_prd1=lr.predict(X_test)

In [24]:
lr_prd1

array([1, 1, 1, ..., 1, 0, 1])

In [25]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,lr_prd1)

0.8276813880126183

In [26]:
# lr_prd1 contains predictions (0 or 1)
pass_fail_labels = np.where(lr_prd1 == 1, "pass", "fail")

#  pass_fail_labels contains "pass" for 1 and "fail" for 0
print(pass_fail_labels)

['pass' 'pass' 'pass' ... 'pass' 'fail' 'pass']


# TASK-2

# ONE MORE Different DATA SET APPLYING THE MODEL

### prediction for hours

In [27]:
pf=pd.read_csv(r"C:\Users\RAHUL\Desktop\kaggledata\newtask.csv")

In [28]:
pf

Unnamed: 0.1  Unnamed: 0 classes attend_date  job code  cost  hours
0                 1           1     AEP  2023-11-10  LSS  ABS     1    8.0
1                18          19     AAP  2023-10-05   PA  PTO     1    4.0
2                42          45     AEP  2023-10-25   PA  ABS     1    8.0
3                54          57     AAP  2023-10-31   PA  ABS     5   40.0
4                59          62     MAP  2023-10-23   PA  ABS     9   72.0
...             ...         ...     ...         ...  ...  ...   ...    ...
19591        396799       22274     AEP  2023-10-06  PMA  PTO     1    8.0
19592        396804       22279     MAP  2023-10-24  LSS  ABS     1    8.0
19593        396848       22330     AEP  2023-10-12   PA  PTO     2   16.0
19594        396853       22336     TPO  2023-10-13  PAN  ABS     1    8.0
19595        396860       22343     IAP  2023-10-06   PA  ABS     1    8.0

[19596 rows x 8 columns]

In [29]:
pf['attend_date'] = pd.to_datetime(pf['attend_date'])

# Extract year, month, and day into separate columns
pf['year'] = pf['attend_date'].dt.year
pf['month'] = pf['attend_date'].dt.month
pf['day'] = pf['attend_date'].dt.day

# Display the resulting DataFrame
print(pf[['attend_date', 'year', 'month','day']])

      attend_date  year  month  day
0      2023-11-10  2023     11   10
1      2023-10-05  2023     10    5
2      2023-10-25  2023     10   25
3      2023-10-31  2023     10   31
4      2023-10-23  2023     10   23
...           ...   ...    ...  ...
19591  2023-10-06  2023     10    6
19592  2023-10-24  2023     10   24
19593  2023-10-12  2023     10   12
19594  2023-10-13  2023     10   13
19595  2023-10-06  2023     10    6

[19596 rows x 4 columns]


In [30]:
pf

Unnamed: 0.1  Unnamed: 0 classes attend_date  job code  cost  hours  \
0                 1           1     AEP  2023-11-10  LSS  ABS     1    8.0   
1                18          19     AAP  2023-10-05   PA  PTO     1    4.0   
2                42          45     AEP  2023-10-25   PA  ABS     1    8.0   
3                54          57     AAP  2023-10-31   PA  ABS     5   40.0   
4                59          62     MAP  2023-10-23   PA  ABS     9   72.0   
...             ...         ...     ...         ...  ...  ...   ...    ...   
19591        396799       22274     AEP  2023-10-06  PMA  PTO     1    8.0   
19592        396804       22279     MAP  2023-10-24  LSS  ABS     1    8.0   
19593        396848       22330     AEP  2023-10-12   PA  PTO     2   16.0   
19594        396853       22336     TPO  2023-10-13  PAN  ABS     1    8.0   
19595        396860       22343     IAP  2023-10-06   PA  ABS     1    8.0   

       year  month  day  
0      2023     11   10  
1      2023     10    5  
2      2023     10   25  
3      2023     10   31  
4      2023     10   23  
...     ...    ...  ...  
19591  2023     10    6  
19592  2023     10   24  
19593  2023     10   12  
19594  2023     10   13  
19595  2023     10    6  

[19596 rows x 11 columns]

In [31]:
pf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19596 entries, 0 to 19595
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   Unnamed: 0.1  19596 non-null  int64         
 1   Unnamed: 0    19596 non-null  int64         
 2   classes       19596 non-null  object        
 3   attend_date   19596 non-null  datetime64[ns]
 4   job           19596 non-null  object        
 5   code          19596 non-null  object        
 6   cost          19596 non-null  int64         
 7   hours         19596 non-null  float64       
 8   year          19596 non-null  int32         
 9   month         19596 non-null  int32         
 10  day           19596 non-null  int32         
dtypes: datetime64[ns](1), float64(1), int32(3), int64(3), object(3)
memory usage: 1.4+ MB


### categorical data is converted into numerical 

In [32]:
from sklearn import preprocessing                    
label_encoder= preprocessing.LabelEncoder()          
pf['classes'] = label_encoder.fit_transform(pf['classes'])    
pf['classes'].value_counts()

#pf['job']=label_encoder.fit_transform(pf['job'])
#pf['job'].value_counts()

#pf['code']=label_encoder.fit_transform(pf['code'])
#pf['code'].value_counts()

classes
0    5070
1    4398
4    3754
3    2754
2    2414
6     792
5     414
Name: count, dtype: int64

In [33]:
pf['job']=label_encoder.fit_transform(pf['job'])
pf['job'].value_counts()

job
2    14615
0     2303
5     1253
3      505
4      456
1      322
6      142
Name: count, dtype: int64

In [34]:
pf['code']=label_encoder.fit_transform(pf['code'])
pf['code'].value_counts()

code
0    11483
3     7874
1      209
2       30
Name: count, dtype: int64

In [35]:
X=pf[["classes","job","code","cost","year","month","day"]]

In [36]:
Y=pf["hours"]

In [37]:
from sklearn.model_selection import train_test_split
X1_train, X1_test, Y1_train, Y1_test =train_test_split(X,Y, test_size=0.2)

In [38]:
from sklearn.linear_model import LinearRegression

In [39]:
reg1=LinearRegression()
reg1.fit(X1_train,Y1_train)

LinearRegression()

In [40]:
lr_prd2=reg1.predict(X1_test)

In [41]:
lr_prd2

array([  7.84318985,   7.87058207,   6.9953411 , ...,  63.85079718,
        31.88186865, 431.96342575])

In [42]:
reg1.score(X1_test,Y1_test)

0.9981168342366439

In [43]:
from sklearn.metrics import accuracy_score,mean_squared_error
mean_squared_error(Y1_test,lr_prd2)

3.577135799389979

# prediction for cost

In [44]:
pf

Unnamed: 0.1  Unnamed: 0  classes attend_date  job  code  cost  hours  \
0                 1           1        1  2023-11-10    0     0     1    8.0   
1                18          19        0  2023-10-05    2     3     1    4.0   
2                42          45        1  2023-10-25    2     0     1    8.0   
3                54          57        0  2023-10-31    2     0     5   40.0   
4                59          62        4  2023-10-23    2     0     9   72.0   
...             ...         ...      ...         ...  ...   ...   ...    ...   
19591        396799       22274        1  2023-10-06    4     3     1    8.0   
19592        396804       22279        4  2023-10-24    0     0     1    8.0   
19593        396848       22330        1  2023-10-12    2     3     2   16.0   
19594        396853       22336        6  2023-10-13    3     0     1    8.0   
19595        396860       22343        3  2023-10-06    2     0     1    8.0   

       year  month  day  
0      2023     11   10  
1      2023     10    5  
2      2023     10   25  
3      2023     10   31  
4      2023     10   23  
...     ...    ...  ...  
19591  2023     10    6  
19592  2023     10   24  
19593  2023     10   12  
19594  2023     10   13  
19595  2023     10    6  

[19596 rows x 11 columns]

In [45]:
from sklearn import preprocessing                    
label_encoder= preprocessing.LabelEncoder()          
pf['classes'] = label_encoder.fit_transform(pf['classes'])    
pf['classes'].value_counts()

#pf['job']=label_encoder.fit_transform(pf['job'])
#pf['job'].value_counts()

#pf['code']=label_encoder.fit_transform(pf['code'])
#pf['code'].value_counts()

classes
0    5070
1    4398
4    3754
3    2754
2    2414
6     792
5     414
Name: count, dtype: int64

In [46]:
pf['job']=label_encoder.fit_transform(pf['job'])
pf['job'].value_counts()


job
2    14615
0     2303
5     1253
3      505
4      456
1      322
6      142
Name: count, dtype: int64

In [47]:
pf['code']=label_encoder.fit_transform(pf['code'])
pf['code'].value_counts()

code
0    11483
3     7874
1      209
2       30
Name: count, dtype: int64

In [48]:
x2=pf[["classes","job","code","hours","year","month","day"]]

In [49]:
y2=pf["cost"]

In [50]:

from sklearn.model_selection import train_test_split
X2_train, X2_test, Y2_train, Y2_test =train_test_split(x2,y2,test_size=0.2)

In [51]:
from sklearn.linear_model import LinearRegression
reg2=LinearRegression()
reg2.fit(X2_train,Y2_train)

LinearRegression()

In [52]:
lr_prd3=reg2.predict(X2_test)

In [53]:
lr_prd3

array([ 0.52440219,  1.02070852, 13.99510338, ...,  1.07806269,
        0.52440219,  0.62283595])

In [54]:
reg2.score(X2_test,Y2_test)

0.9981501886211632

In [55]:
from sklearn.metrics import accuracy_score,mean_squared_error
mean_squared_error(Y2_test,lr_prd3)

0.07634422709816287

In [56]:
from sklearn.metrics import r2_score
r2_score(Y2_test,lr_prd3)

0.9981501886211632