In [47]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [48]:
import warnings
warnings.filterwarnings("ignore")

In [49]:
import tensorflow as tf
from tensorflow import keras

In [50]:
print(tf.__version__)

2.15.0


### Introduction to deep learning:

**Deep learning** is a subfield of machine learning that focuses on algorithms inspired by the structure and function of the human brain, called artificial neural networks. It’s “deep” because the neural networks have many layers, hence the term *deep learning.*
![ML vs DL](mlvsdl.png)

One of differences between machine learning and deep learning model is on the feature extraction area. Feature extraction is done by human in machine learning whereas deep learning model figure out by itself.

#### Artificial Neural Network:

The core building block of deep learning is the **artificial neuron or node**. These neurons are inspired by the neurons in our brain. The idea is simple: take a bunch of inputs, perform some computations on them, and produce an output.

Just like a single neuron in the brain can’t do much on its own, an artificial neuron isn’t incredibly powerful by itself. However, when we start connecting these neurons together into a network, we can accomplish complex tasks.

Each neuron in the network receives inputs, does a computation, and then sends the output to other neurons. The power of neural networks comes from connecting these neurons together and learning the correct weights (the importance assigned to input values) to assign to the inputs.

#### Deep Neural Networks:

A **deep neural network** is a neural network with a certain level of complexity, containing **multiple hidden layers of nodes** between the input and output layers. Here’s a simplified visualization:

**Input layer (features) → Hidden layers → Output layer (prediction)**

The input layer is where the network takes in feature data. The hidden layers are where the network learns through weights and bias adjustments. The output layer is where the final prediction is made.

In [51]:
df=pd.read_csv(r"C:\Users\ganig\OneDrive\Desktop\Dataset\Bank.csv")

In [52]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [53]:
df.count()

RowNumber          10000
CustomerId         10000
Surname            10000
CreditScore        10000
Geography          10000
Gender             10000
Age                10000
Tenure             10000
Balance            10000
NumOfProducts      10000
HasCrCard          10000
IsActiveMember     10000
EstimatedSalary    10000
Exited             10000
dtype: int64

In [54]:
df.shape

(10000, 14)

In [55]:
x=df.iloc[:,3:-1].values

In [56]:
y=df.iloc[:,-1].values

In [57]:
x.shape

(10000, 10)

In [58]:
y.shape

(10000,)

In [59]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [60]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

**Label Encoding the gender column**

In [61]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
x[:,2]= label_encoder.fit_transform(x[:,2])

In [62]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [63]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[1])],remainder="passthrough")
x=np.array(ct.fit_transform(x))


In [64]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [65]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [66]:
x_test.shape

(2000, 12)

In [67]:
x_train.shape

(8000, 12)

In [68]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train= scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)

In [69]:
x_train

array([[ 1.00150113, -0.57946723, -0.57638802, ...,  0.64920267,
         0.97481699,  1.36766974],
       [-0.99850112,  1.72572313, -0.57638802, ...,  0.64920267,
         0.97481699,  1.6612541 ],
       [-0.99850112, -0.57946723,  1.73494238, ...,  0.64920267,
        -1.02583358, -0.25280688],
       ...,
       [ 1.00150113, -0.57946723, -0.57638802, ..., -1.54035103,
        -1.02583358, -0.1427649 ],
       [ 1.00150113, -0.57946723, -0.57638802, ...,  0.64920267,
        -1.02583358, -0.05082558],
       [-0.99850112,  1.72572313, -0.57638802, ...,  0.64920267,
         0.97481699, -0.81456811]])

In [70]:
x_test

array([[-1.02020406,  1.73668197, -0.56349184, ..., -1.57810057,
        -1.0502616 , -0.99096946],
       [ 0.98019606, -0.57581067, -0.56349184, ...,  0.63367318,
         0.95214374,  0.8293793 ],
       [-1.02020406, -0.57581067,  1.77464858, ...,  0.63367318,
        -1.0502616 , -0.69904548],
       ...,
       [ 0.98019606, -0.57581067, -0.56349184, ...,  0.63367318,
        -1.0502616 , -1.13742992],
       [ 0.98019606, -0.57581067, -0.56349184, ...,  0.63367318,
        -1.0502616 , -0.38237688],
       [-1.02020406,  1.73668197, -0.56349184, ...,  0.63367318,
         0.95214374,  0.15573964]])

In [71]:
y_train

array([0, 0, 1, ..., 1, 1, 0], dtype=int64)

In [72]:
ann = tf.keras.models.Sequential()

**Input layer (features) → Hidden layers → Output layer (prediction)**

**Adding the input layer and first hidden layer:**

In [73]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

**Adding the second hidden layer:**

In [74]:
ann.add(tf.keras.layers.Dense(units=8,activation="relu"))

**Adding the output layer:**

In [75]:
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

Training the ANN

**Compiling the ANN:**

In [76]:
#ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accurarcy"])

In [77]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy', 'mse'])

In [78]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5063 - accuracy: 0.7937 - mse: 0.1635
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4701 - accuracy: 0.7945 - mse: 0.1503
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4547 - accuracy: 0.7945 - mse: 0.1450
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4430 - accuracy: 0.7945 - mse: 0.1409
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4347 - accuracy: 0.8014 - mse: 0.1379
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4286 - accuracy: 0.8105 - mse: 0.1352
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4238 - accuracy: 0.8176 - mse: 0.1331
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4194 - accuracy: 0.8229 - mse: 0.1314
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.415

**predicting the result on single observation or single customer:**

In [79]:
print(ann.predict(scaler.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 [==============================] - 0s 97ms/step
[[False]]


**predicting the test set results:**

In [80]:
y_pred = ann.predict(x_test)
print(y_pred>0.5)

63/63 [==============================] - 0s 1ms/step
[[False]
 [False]
 [False]
 ...
 [ True]
 [False]
 [False]]


**confusion matrix**

In [81]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred_binary = (y_pred > 0.5).astype(int)  # Convert probabilities to binary predictions
cm = confusion_matrix(y_test, y_pred_binary)
accuracy = accuracy_score(y_test, y_pred_binary)
print("Confusion Matrix:")
print(cm)
print("Accuracy:", accuracy)

Confusion Matrix:
[[1533   74]
 [ 211  182]]
Accuracy: 0.8575
